name: myplans
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  firebase_database: ^10.0.3
  firebase_storage: ^11.0.3
  shared_preferences: ^2.0.15
  fluttertoast: ^8.1.1
  image_picker: ^0.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
